name = "LineIntegrals"
uuid = "2c651c0d-f5be-416b-b771-ab860150eb63"
authors = ["Mike Ingold <mike.ingold@gmail.com>"]
version = "0.2.0"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
