name = "MeshIntegrals"
uuid = "dadec2fd-bbe0-4da4-9dbe-476c782c8e47"
authors = ["Mike Ingold <mike.ingold@gmail.com>"]
version = "0.9.4"

[deps]
FastGaussQuadrature = "442a2c76-b920-505d-bb47-c5924d526838"
HCubature = "19dc6840-f33b-545b-b366-655c7e3ffd49"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"

[compat]
DynamicQuantities = "0.11.3"
FastGaussQuadrature = "1"
HCubature = "1.5"
julia = "1.6"
Meshes = "0.36 - 0.40"
QuadGK = "2"

[extras]
DynamicQuantities = "06fc5a27-2a28-4c7c-a15d-362465fb6821"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[targets]
test = ["DynamicQuantities", "Meshes", "Test", "Unitful"]
